##########################################################################
#                                                                        #
#                          Service Identity Part                         #
#               For Further information, please check README             #
#                                                                        #
##########################################################################

service:
  http:
    host: "0.0.0.0"
    port: "8080"
    requestTimeout: 32

##########################################################################
#                                                                        #
#                         Server Config Part                             #
#       Please set the server parameters based on your own settings      #
#                                                                        #
##########################################################################


postgres:
  username: "gopia"
  password: "gopia69"
  host: "127.0.0.1"
  port: "5432"
  db: "gopia2"
  sslmode: "disable"
  timezone: "UTC"
