##########################################################################
#                                                                        #
#                          Service Identity Part                         #
#               For Further information, please check README             #
#                                                                        #
##########################################################################

service:
  http:
    host: "0.0.0.0"
    port: "8080"
    requestTimeout: 32
    allowOrigin: "*"
  token:
    password: "2791d21ddfc53f1bccbe2cf6ec4efb2042cd6cb2ad737c4f724d66fc2cd01fd0"
    expiration: 3600

##########################################################################
#                                                                        #
#                         Server Config Part                             #
#       Please set the server parameters based on your own settings      #
#                                                                        #
##########################################################################


postgres:
  username: "gopia"
  password: "gopia69"
  # host: "127.0.0.1"
  host: "db"
  port: "5432"
  db: "gopia2"
  sslmode: "disable"
  timezone: "UTC"

